<template><div class="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
  <header><h1 class="text-xl font-semibold text-slate-900">{{ isWarehouse ? 'Warehouse Returns' : 'Inventory Stock Returns' }}</h1><p class="mt-1 text-sm text-slate-500">Customer returns assigned for delivery to {{ isWarehouse ? 'warehouse' : 'store' }} locations.</p></header>
  <Card class="rounded-2xl border border-slate-200 shadow-sm"><template #content><div class="grid gap-3 p-5 md:grid-cols-3"><InputText v-model="search" placeholder="Search return, order, or customer" fluid @keyup.enter="load"/><Select v-model="status" :options="statuses" optionLabel="label" optionValue="value" fluid/><div class="flex gap-2"><Button label="Apply" icon="pi pi-filter" class="flex-1" :loading="loading" @click="load"/><Button icon="pi pi-filter-slash" outlined @click="clear"/></div></div></template></Card>
  <Card class="rounded-2xl border border-slate-200 shadow-sm"><template #content><div class="p-5"><DataTable :value="rows" :loading="loading" paginator :rows="10" stripedRows responsiveLayout="scroll">
    <Column header="Return"><template #body="{data}"><button class="font-semibold text-blue-600 hover:underline" @click="open(data)">{{ data.return_request?.return_number || `Return #${data.return_id}` }}</button><small class="block text-slate-500">Order {{ data.return_request?.order?.order_number || '-' }}</small></template></Column>
    <Column header="Customer"><template #body="{data}">{{ data.pickup_name || data.return_request?.order?.shipping_name || '-' }}<small class="block text-slate-500">{{ data.pickup_phone || data.return_request?.order?.shipping_phone || '-' }}</small></template></Column>
    <Column header="Item"><template #body="{data}">{{ data.return_request?.order_item?.product_name || '-' }}<small class="block text-slate-500">{{ data.return_request?.order_item?.sku || '-' }} · Qty {{ data.return_request?.requested_quantity || 1 }}</small></template></Column>
    <Column header="Destination"><template #body="{data}"><span class="font-medium">{{ data.destination_branch?.name || '-' }}</span><small class="block text-slate-500">{{ data.destination_branch?.address || '-' }}</small></template></Column>
    <Column header="Driver"><template #body="{data}">{{ [data.driver?.fname,data.driver?.lname].filter(Boolean).join(' ') || 'Unassigned' }}</template></Column>
    <Column header="Status"><template #body="{data}"><Tag :value="label(data.status)" :severity="severity(data.status)"/></template></Column>
    <Column header="Action"><template #body="{data}"><Button v-if="data.return_request?.return_type === 'replacement'" label="Process Replacement" severity="warn" size="small" @click="openReplacement(data)"/><Button v-else icon="pi pi-eye" text rounded @click="open(data)"/></template></Column>
    <template #empty><div class="py-10 text-center text-slate-500">No customer returns assigned to this destination type.</div></template>
  </DataTable></div></template></Card>
</div></template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'; import { useRouter } from 'vue-router'; import { useToast } from 'primevue/usetoast'; import axiosClient from '@/axios'; import Card from 'primevue/card'; import Button from 'primevue/button'; import InputText from 'primevue/inputtext'; import Select from 'primevue/select'; import DataTable from 'primevue/datatable'; import Column from 'primevue/column'; import Tag from 'primevue/tag'
const props=defineProps<{mode:'warehouse'|'inventory'}>(); const router=useRouter(),toast=useToast(),isWarehouse=computed(()=>props.mode==='warehouse'),loading=ref(false),rows=ref<any[]>([]),search=ref(''),status=ref(''); const statuses=[{label:'All Statuses',value:''},{label:'Assigned',value:'assigned'},{label:'Picked Up',value:'picked_up'},{label:'Out for Delivery',value:'out_for_delivery'},{label:'Delivered',value:'delivered'}]; const label=(v:any)=>String(v||'-').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()); const severity=(v:string)=>v==='delivered'?'success':v==='out_for_delivery'?'info':v==='picked_up'?'warn':'secondary'; const load=async()=>{loading.value=true;try{const url=isWarehouse.value?'/api/warehouse/returns':'/api/inventory/returns/customer/destinations';const r=await axiosClient.get(url,{params:{search:search.value||undefined,status:status.value||undefined}});rows.value=r.data?.data||[]}catch(e:any){toast.add({severity:'error',summary:'Load Failed',detail:e?.response?.data?.message||'Unable to load destination returns.',life:3000})}finally{loading.value=false}};const clear=()=>{search.value='';status.value='';load()};const open=(row:any)=>router.push({name:'logistics.return-pickups.detail',params:{id:row.id}});const openReplacement=(row:any)=>router.push({name:isWarehouse.value?'warehouse.replacements.detail':'inventory.replacements.detail',params:{id:row.return_id}});onMounted(load)
</script>
