<template>
  <div class="min-h-screen p-4"><ConfirmDialog/><div class="mx-auto max-w-7xl space-y-4">
    <div class="flex items-center gap-3"><Button icon="pi pi-arrow-left" severity="secondary" text @click="goBack"/><div><h1 class="text-xl font-bold text-slate-800">Create Warehouse Purchase Requisition</h1><p class="text-xs text-slate-500">Request replenishment for a warehouse branch.</p></div></div>
    <Card class="border border-slate-200 shadow-sm"><template #content><form class="space-y-5" @submit.prevent="confirmSubmit">
      <div class="grid gap-4 md:grid-cols-2">
        <div class="flex flex-col gap-1.5"><label class="text-xs font-semibold text-slate-700">Warehouse Branch</label><Select v-model="form.branch_id" :options="branches" optionLabel="name" optionValue="id" placeholder="Select warehouse branch" fluid :loading="loading" @change="resetItems"/><small v-if="errors.branch_id" class="text-red-500">{{ errors.branch_id }}</small></div>
        <div class="flex flex-col gap-1.5"><label class="text-xs font-semibold text-slate-700">Reason / Notes</label><Textarea v-model="form.reason" rows="2" placeholder="Why is replenishment required?"/><small v-if="errors.reason" class="text-red-500">{{ errors.reason }}</small></div>
      </div>
      <div class="rounded-lg border border-slate-200 p-3"><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-semibold text-slate-800">Line Items</h2><Button type="button" label="Add Item" icon="pi pi-plus" size="small" :disabled="!form.branch_id" @click="addItem"/></div>
        <DataTable :value="form.items" rowHover responsiveLayout="scroll" class="text-sm">
          <template #empty><div class="py-8 text-center text-slate-500">Select a warehouse branch and add an item.</div></template>
          <Column header="Inventory Item" style="min-width:300px"><template #body="{data,index}"><Select v-model="data.branch_inventory_id" :options="inventoryOptions" optionLabel="searchText" optionValue="value" filter fluid placeholder="Select product" @change="selectItem(index)"><template #option="{option}"><div><div class="font-medium">{{ option.title }}</div><small class="text-slate-500">{{ option.subtitle }}</small></div></template></Select></template></Column>
          <Column header="Available"><template #body="{data}">{{ stock(data)?.quantity_available ?? '—' }}</template></Column>
          <Column header="Requested Qty"><template #body="{data}"><InputNumber v-model="data.quantity_requested" :min="1" :useGrouping="false" fluid/></template></Column>
          <Column header="Unit"><template #body="{data}">{{ stock(data)?.product?.unit_of_measurement || '—' }}</template></Column>
          <Column header="Unit Cost"><template #body="{data}">{{ money(unitCost(stock(data))) }}</template></Column>
          <Column header="Supplier"><template #body="{data}"><Select v-model="data.selected_supplier_id" :options="supplierOptions(data)" optionLabel="label" optionValue="value" placeholder="None" showClear filter fluid/></template></Column>
          <Column style="width:70px"><template #body="{index}"><Button type="button" icon="pi pi-trash" severity="danger" text size="small" @click="removeItem(index)"/></template></Column>
        </DataTable><small v-if="errors.items" class="mt-2 block text-red-500">{{ errors.items }}</small>
      </div>
      <div class="flex justify-end gap-2 border-t border-slate-200 pt-4"><Button type="button" label="Cancel" severity="secondary" size="small" @click="goBack"/><Button type="submit" label="Create Request" size="small" :loading="saving"/></div>
    </form></template></Card>
  </div></div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { router } from '@inertiajs/vue3';import { useConfirm } from 'primevue/useconfirm';import { useToast } from 'primevue/usetoast';import ConfirmDialog from 'primevue/confirmdialog';import WarehouseService from '@/services/warehouse.service'
const confirm=useConfirm(),toast=useToast(),loading=ref(true),saving=ref(false),branches=ref<any[]>([]),inventory=ref<any[]>([]),errors=reactive<Record<string,string>>({});const form=reactive<any>({branch_id:null,reason:'',items:[]});const branchInventory=computed(()=>inventory.value.filter(row=>Number(row.branch_id)===Number(form.branch_id)));const inventoryOptions=computed(()=>branchInventory.value.map(row=>{const name=row.product?.product_name||'Unknown',sku=row.variation?.variation_sku||row.product?.sku||'—';return{value:row.id,title:`${name}${row.variation?.variation_name?` - ${row.variation.variation_name}`:''}`,subtitle:`SKU: ${sku} | Stock: ${row.quantity_available||0}`,searchText:`${name} ${sku}`}}))
const blank=()=>({branch_inventory_id:null,quantity_requested:1,selected_supplier_id:null}),addItem=()=>form.items.push(blank()),removeItem=(i:number)=>form.items.splice(i,1),resetItems=()=>{form.items=[blank()]};const stock=(item:any)=>inventory.value.find(row=>Number(row.id)===Number(item.branch_inventory_id));const unitCost=(row:any)=>Number(row?.product?.cost_price??0);const money=(v:any)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(v||0));const supplierOptions=(item:any)=>(stock(item)?.product?.suppliers||[]).map((s:any)=>({value:s.id,label:s.supplier_name||s.company_name||`Supplier #${s.id}`}));const selectItem=(i:number)=>{const row=stock(form.items[i]);form.items[i].quantity_requested=Number(row?.reorder_quantity||1);form.items[i].selected_supplier_id=null};const goBack=()=>router.visit('/warehouse-operations/stock')
const submit=async()=>{Object.keys(errors).forEach(k=>delete errors[k]);const items=form.items.filter((i:any)=>i.branch_inventory_id&&i.quantity_requested>0);if(!form.branch_id)errors.branch_id='Select a warehouse branch.';if(!form.reason.trim())errors.reason='Reason is required.';if(!items.length)errors.items='Add at least one valid item.';if(Object.keys(errors).length)return;saving.value=true;try{await WarehouseService.createPurchaseRequisition({branch_id:form.branch_id,reason:form.reason,items});toast.add({severity:'success',summary:'Created',detail:'Warehouse purchase requisition submitted.',life:3000});goBack()}catch(e:any){toast.add({severity:'error',summary:'Unable to Create',detail:e?.response?.data?.message||'Purchase requisition could not be created.',life:4500})}finally{saving.value=false}};const confirmSubmit=()=>confirm.require({header:'Create Purchase Requisition?',message:'Submit this warehouse replenishment request to Procurement?',icon:'pi pi-question-circle',rejectLabel:'No',acceptLabel:'Confirm',accept:submit})
onMounted(async()=>{try{const data=await WarehouseService.purchaseRequisitionOptions();branches.value=data.branches||[];inventory.value=data.inventory||[];if(branches.value.length===1){form.branch_id=branches.value[0].id;resetItems()}}finally{loading.value=false}})
</script>
