<template>
  <div class="space-y-4 text-xs">
    <div><h2 class="text-lg font-semibold text-slate-900">Payroll Settings</h2><p class="text-slate-500">Configure company-wide payroll, attendance, overtime, and holiday rules.</p></div>
    <Tabs v-model:value="tab"><TabList><Tab value="general">General</Tab><Tab value="attendance">Attendance & Overtime</Tab><Tab value="rules">Payroll Rules</Tab><Tab value="holidays">Holidays</Tab></TabList><TabPanels>
      <TabPanel value="general"><section class="space-y-4"><h3 class="font-semibold">Company Defaults</h3><div class="grid gap-3 md:grid-cols-2"><div><label>Payroll schedule</label><Select v-model="form.schedule" :options="schedules" optionLabel="label" optionValue="value" class="mt-1 w-full" size="small" /></div><div><label>Currency</label><Select v-model="form.currency" :options="['PHP']" class="mt-1 w-full" size="small" /></div><div><label>Default work start</label><InputText v-model="form.workStart" type="time" class="mt-1 w-full" size="small" /></div><div><label>Default work end</label><InputText v-model="form.workEnd" type="time" class="mt-1 w-full" size="small" /></div><div><label>Default lunch break (minutes)</label><InputNumber v-model="form.lunchBreak" class="mt-1 w-full" size="small" /></div><div><label>Default paid shift hours</label><InputNumber v-model="form.paidHours" :min="0" :max="24" class="mt-1 w-full" size="small" /></div></div><Button label="Save Settings" severity="warn" size="small" :loading="saving" @click="save" /></section></TabPanel>
      <TabPanel value="attendance"><section class="space-y-4"><h3 class="font-semibold">Attendance Rules</h3><div class="grid gap-3 md:grid-cols-2"><div><label>Grace period (minutes)</label><InputNumber v-model="form.gracePeriod" class="mt-1 w-full" size="small" /></div><div><label>Paid break duration</label><InputNumber v-model="form.paidBreak" class="mt-1 w-full" size="small" /></div><div><label>Lunch start</label><InputText v-model="form.lunchStart" type="time" class="mt-1 w-full" size="small" /></div><div><label>Lunch duration</label><InputNumber v-model="form.lunchDuration" class="mt-1 w-full" size="small" /></div><div><label>OT break after (hours)</label><InputNumber v-model="form.otBreakAfter" class="mt-1 w-full" size="small" /></div><div><label>OT break duration</label><InputNumber v-model="form.otBreakDuration" class="mt-1 w-full" size="small" /></div></div><div class="flex flex-wrap gap-4"><label v-for="item in toggles" :key="item.key" class="flex items-center gap-2"><InputSwitch v-model="form[item.key]" />{{ item.label }}</label></div><div class="grid gap-3 md:grid-cols-2"><div v-for="item in ['weekdayOt', 'weekendOt']" :key="item"><label>{{ item === 'weekdayOt' ? 'Weekday overtime rate' : 'Weekend/rest day overtime rate' }}</label><div class="mt-1 grid grid-cols-2 gap-2"><InputNumber v-model="form[item].multiplier" placeholder="Multiplier" :disabled="form[item].exact" size="small" /><InputNumber v-model="form[item].exact" placeholder="Exact/hour" :disabled="form[item].multiplier" size="small" /></div></div></div><Button label="Save Settings" severity="warn" size="small" :loading="saving" @click="save" /></section></TabPanel>
      <TabPanel value="rules"><section class="space-y-4"><h3 class="font-semibold">Payroll Rules</h3><div class="grid gap-3 md:grid-cols-2"><div v-for="item in multiplierFields" :key="item.key"><label>{{ item.label }} (x)</label><InputNumber v-model="form[item.key]" :min="0" :step="0.05" class="mt-1 w-full" size="small" /></div><div><label>Night differential start</label><InputText v-model="form.nightStart" type="time" class="mt-1 w-full" size="small" /></div><div><label>Night differential end</label><InputText v-model="form.nightEnd" type="time" class="mt-1 w-full" size="small" /></div><div><label>Night differential rate (%)</label><InputNumber v-model="form.nightRate" suffix=" %" class="mt-1 w-full" size="small" /></div><div><label>Government contribution schedule</label><Select v-model="form.contributionSchedule" :options="contributionSchedules" optionLabel="label" optionValue="value" class="mt-1 w-full" size="small" /></div></div><Button label="Save Settings" severity="warn" size="small" :loading="saving" @click="save" /></section></TabPanel>
      <TabPanel value="holidays"><section class="space-y-4"><div class="flex items-center justify-between"><div><h3 class="font-semibold">Company Holidays</h3><p class="text-slate-500">Import Philippine public holidays or add store-specific holidays.</p></div><div class="flex gap-2"><Button label="Import PH" severity="secondary" outlined size="small" :loading="holidayLoading" @click="importPH" /><Button label="Add Holiday" severity="warn" size="small" @click="openHolidayDialog" /></div></div><DataTable :value="holidays" size="small" class="text-xs"><template #empty><div class="py-8 text-center text-slate-500">No holidays recorded.</div></template><Column field="holiday_date" header="Date"><template #body="{ data }">{{ formatHolidayDate(data.holiday_date) }}</template></Column><Column field="name" header="Name" /><Column field="holiday_type" header="Type"><template #body="{ data }"><Tag :value="holidayTypeLabel(data)" :severity="holidayTypeSeverity(data)" class="text-xs" /></template></Column><Column field="applies_to" header="Applies To"><template #body="{ data }">{{ appliesToLabel(data) }}</template></Column><Column header="Actions"><template #body="{ data }"><Button icon="pi pi-pencil" text size="small" @click="editHoliday(data)" /><Button icon="pi pi-trash" text severity="danger" size="small" @click="removeHoliday(data)" /></template></Column></DataTable></section></TabPanel>
    </TabPanels></Tabs>
    <Dialog v-model:visible="holidayDialog" modal :header="holidayForm.id ? 'Edit Holiday' : 'Add Holiday'" :style="{ width: '32rem' }"><div class="space-y-3"><DatePicker v-model="holidayForm.date" dateFormat="MM dd, yy" showIcon class="w-full" size="small" /><InputText v-model="holidayForm.name" placeholder="Holiday name" class="w-full" size="small" /><Select v-model="holidayForm.type" :options="holidayTypes" optionLabel="label" optionValue="value" placeholder="Type" class="w-full" size="small" /><Select v-model="holidayForm.applies" :options="appliesOptions" optionLabel="label" optionValue="value" placeholder="Applies to" class="w-full" size="small" /><Select v-if="holidayForm.applies === 'city'" v-model="holidayForm.city" :options="caviteCities" filter placeholder="City in Cavite" class="w-full" size="small" /><MultiSelect v-if="holidayForm.applies === 'branches'" v-model="holidayForm.branch_ids" :options="branchOptions" optionLabel="name" optionValue="id" filter display="chip" placeholder="Select branches" class="w-full" size="small" /></div><template #footer><Button label="Cancel" severity="secondary" text @click="holidayDialog = false" /><Button label="Save" severity="warn" size="small" @click="saveHoliday" /></template></Dialog>
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'; import hrService from '@/services/hr.services'; import { useToast } from 'primevue/usetoast'; import DatePicker from 'primevue/datepicker'; import InputNumber from 'primevue/inputnumber'; import InputText from 'primevue/inputtext'; import Select from 'primevue/select'; import MultiSelect from 'primevue/multiselect'; import Tag from 'primevue/tag'; import Dialog from 'primevue/dialog'; import Button from 'primevue/button'; import InputSwitch from 'primevue/inputswitch';
const branchOptions = ref<any[]>([])
const formatHolidayDate = (value: string) => value ? new Intl.DateTimeFormat('en-PH', { month: 'long', day: 'numeric', year: 'numeric' }).format(new Date(`${value.slice(0, 10)}T00:00:00`)) : '-'
const holidayTypeLabel = (item: any) => item.holiday_type === 'regular' ? 'Regular' : item.holiday_type === 'company' ? 'Company' : item.is_working_holiday ? 'Special Working' : 'Special Non-working'
const holidayTypeSeverity = (item: any) => item.holiday_type === 'regular' ? 'danger' : item.holiday_type === 'company' ? 'info' : item.is_working_holiday ? 'warn' : 'success'
const appliesToLabel = (item: any) => item.applies_to === 'city' ? `City: ${item.city || '-'}` : item.applies_to === 'branches' ? 'Selected branches' : item.applies_to === 'company' ? 'Whole company' : 'All employees'
const toLocalDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const toast = useToast(); const tab = ref('general'); const saving = ref(false); const holidayLoading = ref(false); const holidayDialog = ref(false); const holidays = ref<any[]>([]); const schedules = [{ label: 'Monthly', value: 'monthly' }, { label: 'Semi-monthly', value: 'semi_monthly' }, { label: 'Weekly', value: 'weekly' }]; const contributionSchedules = [{ label: 'Monthly End Only', value: 'monthly_end' }, { label: 'First Cutoff Only', value: 'first_cutoff' }, { label: 'Second Cutoff Only', value: 'second_cutoff' }, { label: 'Every Payroll Run', value: 'every_run' }]; const multiplierFields = [{ label: 'Regular - Worked', key: 'regularWorked' }, { label: 'Regular - Unworked', key: 'regularUnworked' }, { label: 'Special - Worked', key: 'specialWorked' }, { label: 'Special - Unworked', key: 'specialUnworked' }]; const holidayTypes = [{ label: 'Regular', value: 'regular' }, { label: 'Special Non-working', value: 'special_non_working' }, { label: 'Special Working', value: 'special_working' }]; const appliesOptions = [{ label: 'All employees', value: 'all' }, { label: 'Employees in City', value: 'city' }, { label: 'Selected Branches', value: 'branches' }, { label: 'Whole Company', value: 'company' }]; const caviteCities = ['Bacoor', 'Cavite City', 'Dasmarinas', 'General Trias', 'Imus', 'Kawit', 'Silang', 'Tagaytay', 'Tanza', 'Trece Martires']; const form = ref<any>({ schedule: 'semi_monthly', currency: 'PHP', workStart: '08:00', workEnd: '17:00', lunchBreak: 60, paidHours: 8, gracePeriod: 5, paidBreak: 15, lunchStart: '12:00', lunchDuration: 60, otBreakAfter: 4, otBreakDuration: 30, unusedLunchPaid: false, autoDeductUndertime: true, enableOvertime: true, earlyClockInPaid: false, approvedOtOnly: true, weekdayOt: { multiplier: 1.25, exact: null }, weekendOt: { multiplier: 1.3, exact: null }, regularWorked: 2, regularUnworked: 1, specialWorked: 1.3, specialUnworked: 0, nightStart: '22:00', nightEnd: '06:00', nightRate: 10, contributionSchedule: 'second_cutoff' }); const holidayForm = ref<any>({ date: null, name: '', type: 'regular', applies: 'all', city: '', branches: '' });
const load = async () => { try { const [r, branches] = await Promise.all([hrService.getHrSettings(), hrService.getBranches()]); form.value = { ...form.value, ...(r?.data?.payroll_configuration || {}) }; branchOptions.value = branches?.data || branches || []; await loadHolidays() } catch (_) {} }
const save = async () => { saving.value = true; try { await hrService.updateHrSettings({ payroll_configuration: form.value }); toast.add({ severity: 'success', summary: 'Saved', detail: 'Payroll settings updated.', life: 2500 }) } finally { saving.value = false } }
const loadHolidays = async () => { const r = await hrService.api.get('api/holidays'); holidays.value = r.data?.data || [] }
const importPH = async () => { holidayLoading.value = true; try { await hrService.api.post('api/holidays/import-ph'); await loadHolidays(); toast.add({ severity: 'success', summary: 'Imported', detail: 'Philippine holidays imported.', life: 2500 }) } finally { holidayLoading.value = false } }
const openHolidayDialog = () => { holidayForm.value = { id: null, date: null, name: '', type: 'regular', applies: 'all', city: '', branch_ids: [] }; holidayDialog.value = true }
const saveHoliday = async () => {
  if (!holidayForm.value.date || !holidayForm.value.name) return
  const payload = { name: holidayForm.value.name, holiday_date: toLocalDate(holidayForm.value.date), holiday_type: holidayForm.value.type, applies_to: holidayForm.value.applies, city: holidayForm.value.city || null, branch_ids: holidayForm.value.branch_ids || [] }
  if (holidayForm.value.id) await hrService.api.put(`api/holidays/${holidayForm.value.id}`, payload)
  else await hrService.api.post('api/holidays', payload)
  holidayDialog.value = false; await loadHolidays()
}
const editHoliday = (item: any) => { holidayForm.value = { id: item.id, date: new Date(`${item.holiday_date.slice(0, 10)}T00:00:00`), name: item.name, type: item.holiday_type === 'special' ? (item.is_working_holiday ? 'special_working' : 'special_non_working') : item.holiday_type, applies: item.applies_to || 'all', city: item.city || '', branch_ids: item.branch_ids || [] }; holidayDialog.value = true }
const removeHoliday = async (item: any) => { await hrService.api.delete(`api/holidays/${item.id}`); await loadHolidays() }
onMounted(load)
const toggles = [{ key: 'unusedLunchPaid', label: 'Unused lunch is paid' }, { key: 'autoDeductUndertime', label: 'Auto-deduct undertime' }, { key: 'enableOvertime', label: 'Enable overtime' }, { key: 'earlyClockInPaid', label: 'Pay early clock-in' }, { key: 'approvedOtOnly', label: 'Pay approved OT only' }]
</script>
