<template>
  <div class="mx-auto max-w-7xl space-y-6 pb-10">
    <Button label="Back to customers" icon="pi pi-arrow-left" severity="secondary" text @click="router.back()"/>
    <div v-if="loading" class="space-y-4"><Skeleton height="12rem" border-radius="1.5rem"/><Skeleton height="20rem" border-radius="1.5rem"/></div>
    <template v-else-if="customer">
      <section class="relative overflow-hidden rounded-3xl bg-slate-950 px-7 py-8 text-white shadow-xl">
        <div class="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-sky-400/20 blur-3xl"></div>
        <div class="relative flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div class="flex items-center gap-5"><span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-sky-300 text-xl font-bold text-slate-950">{{ initials(name) }}</span><div><p class="text-xs font-bold uppercase tracking-[.2em] text-sky-300">{{ code }}</p><h1 class="mt-2 text-3xl font-bold">{{ name }}</h1><p class="mt-2 text-sm text-slate-300">Customer account verification profile</p></div></div><div class="flex flex-wrap gap-2"><Tag :value="customer.email_verified_at ? 'Email verified' : 'Email unverified'" :severity="customer.email_verified_at ? 'success' : 'warn'" rounded/><Tag :value="customer.is_active ? 'Active' : 'Disabled'" :severity="customer.is_active ? 'success' : 'danger'" rounded/></div></div>
      </section>
      <section class="grid gap-6 lg:grid-cols-[1.2fr_.8fr]">
        <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Customer information</p><h2 class="mt-2 text-xl font-bold text-slate-900">Identity and contact</h2><dl class="mt-6 grid gap-6 sm:grid-cols-2"><Info label="First name" :value="customer.fname"/><Info label="Last name" :value="customer.lname"/><Info label="Email address" :value="customer.email"/><Info label="Phone number" :value="customer.customer?.contact_number || customer.phone_number"/><Info label="Birthday" :value="date(customer.birthday)"/><Info label="Role" :value="customer.role?.display_name || customer.role?.name"/></dl></div>
        <div class="space-y-6"><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Verification signals</p><div class="mt-5 space-y-4"><Signal icon="pi-envelope" label="Email address" :value="customer.email_verified_at ? `Verified ${date(customer.email_verified_at)}` : 'Not verified'" :good="!!customer.email_verified_at"/><Signal icon="pi-lock" label="Account access" :value="customer.is_active ? 'Account is active' : 'Account is disabled'" :good="!!customer.is_active"/></div></div><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Account timeline</p><dl class="mt-5 space-y-4"><Info label="Registered" :value="dateTime(customer.created_at)"/><Info label="Last updated" :value="dateTime(customer.updated_at)"/></dl></div></div>
      </section>
    </template>
    <div v-else class="rounded-3xl border border-slate-200 bg-white py-16 text-center"><h2 class="font-bold text-slate-800">Customer not found</h2></div>
  </div>
</template>
<script setup lang="ts">
import { computed, defineComponent, h, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import Button from 'primevue/button'; import Skeleton from 'primevue/skeleton'; import Tag from 'primevue/tag'; import axiosClient from '../../../axios'
const Info=defineComponent({props:{label:String,value:[String,Number]},setup:p=>()=>h('div',[h('dt',{class:'text-xs font-semibold uppercase tracking-wider text-slate-400'},p.label),h('dd',{class:'mt-2 break-words font-medium text-slate-800'},p.value||'Not provided')])}); const Signal=defineComponent({props:{icon:String,label:String,value:String,good:Boolean},setup:p=>()=>h('div',{class:'flex gap-3'},[h('span',{class:`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${p.good?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`},[h('i',{class:`pi ${p.icon}`})]),h('div',[h('p',{class:'font-semibold text-slate-800'},p.label),h('p',{class:'mt-1 text-sm text-slate-500'},p.value)])])})
const route=useRoute(),router=useRouter(),customer=ref<any>(null),loading=ref(true); const name=computed(()=>customer.value?.full_name||`${customer.value?.fname||''} ${customer.value?.lname||''}`.trim()||'Unknown customer'); const code=computed(()=>customer.value?.user_id||`CUST-${String(customer.value?.id||'').padStart(6,'0')}`); const initials=(v:string)=>v.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(); const date=(v:any)=>v?new Intl.DateTimeFormat('en-PH',{dateStyle:'medium'}).format(new Date(v)):'Not provided'; const dateTime=(v:any)=>v?new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'Not provided'; onMounted(async()=>{try{const r=await axiosClient.get(`/api/admin/customers/${route.params.id}`);customer.value=r.data?.data||null}finally{loading.value=false}})
</script>
