<template>
  <div class="bg-gray-50 min-h-screen p-6">
    <div class="max-w-6xl mx-auto">
      <!-- Header -->
      <div class="mb-6">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-4">
            <Button
              icon="pi pi-arrow-left"
              severity="secondary"
              text
              @click="goBack"
              v-tooltip.top="'Back to Reorder Suggestions'"
            />
            <div>
              <h1 class="text-3xl font-bold text-gray-800">{{ reorderSuggestion?.product?.name }}</h1>
              <p class="text-gray-600 mt-1">Reorder suggestion details and actions</p>
            </div>
          </div>
          <div class="flex gap-2" v-if="reorderSuggestion?.status === 'pending'">
            <Button
              label="Approve & Order"
              icon="pi pi-check"
              severity="success"
              @click="approveSuggestion"
            />
            <Button
              label="Reject"
              icon="pi pi-times"
              severity="danger"
              outlined
              @click="rejectSuggestion"
            />
          </div>
        </div>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="flex justify-center items-center h-64">
        <ProgressSpinner />
      </div>

      <!-- Reorder Suggestion Details -->
      <div v-else-if="reorderSuggestion" class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Main Content -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Basic Information -->
          <Card>
            <template #title>
              <div class="flex items-center gap-2">
                <i class="pi pi-info-circle"></i>
                Suggestion Details
              </div>
            </template>
            <template #content>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label class="block text-sm font-medium text-gray-700">Product</label>
                  <p class="text-lg font-semibold text-gray-900">{{ reorderSuggestion.product?.name }}</p>
                  <p class="text-sm text-gray-600">{{ reorderSuggestion.product?.code }}</p>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Warehouse</label>
                  <p class="text-lg font-semibold text-gray-900">{{ reorderSuggestion.warehouse?.name }}</p>
                  <p class="text-sm text-gray-600">{{ reorderSuggestion.warehouse?.code }}</p>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Status</label>
                  <Tag
                    :value="reorderSuggestion.status"
                    :severity="getStatusSeverity(reorderSuggestion.status)"
                    class="capitalize"
                  />
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Priority</label>
                  <Tag
                    :value="reorderSuggestion.priority"
                    :severity="getPrioritySeverity(reorderSuggestion.priority)"
                    class="capitalize"
                  />
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Generated At</label>
                  <p class="text-lg font-semibold text-gray-900">{{ formatDateTime(reorderSuggestion.generated_at) }}</p>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Generated By</label>
                  <p class="text-lg font-semibold text-gray-900">{{ reorderSuggestion.generated_by_user?.name || 'System' }}</p>
                </div>
              </div>
            </template>
          </Card>

          <!-- Stock Analysis -->
          <Card>
            <template #title>
              <div class="flex items-center gap-2">
                <i class="pi pi-chart-line"></i>
                Stock Analysis
              </div>
            </template>
            <template #content>
              <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                <div class="text-center">
                  <div class="text-3xl font-bold text-blue-600">{{ reorderSuggestion.current_stock || 0 }}</div>
                  <div class="text-sm text-gray-600">Current Stock</div>
                </div>
                <div class="text-center">
                  <div class="text-3xl font-bold text-green-600">{{ reorderSuggestion.suggested_quantity }}</div>
                  <div class="text-sm text-gray-600">Suggested Quantity</div>
                </div>
                <div class="text-center">
                  <div class="text-3xl font-bold text-purple-600">{{ reorderSuggestion.reorder_point || 0 }}</div>
                  <div class="text-sm text-gray-600">Reorder Point</div>
                </div>
                <div class="text-center">
                  <div class="text-3xl font-bold text-orange-600">{{ reorderSuggestion.projected_stock || 0 }}</div>
                  <div class="text-sm text-gray-600">Projected Stock</div>
                </div>
              </div>

              <!-- Stock Level Visualization -->
              <div class="mt-6">
                <div class="flex items-center justify-between text-sm text-gray-600 mb-2">
                  <span>Stock Level</span>
                  <span>{{ reorderSuggestion.current_stock || 0 }} / {{ reorderSuggestion.reorder_point || 0 }}</span>
                </div>
                <div class="w-full bg-gray-200 rounded-full h-3">
                  <div
                    class="bg-gradient-to-r from-red-500 via-yellow-500 to-green-500 h-3 rounded-full transition-all duration-300"
                    :style="{ width: stockLevelPercentage + '%' }"
                  ></div>
                </div>
                <div class="flex justify-between text-xs text-gray-500 mt-1">
                  <span>Low</span>
                  <span>Reorder Point</span>
                  <span>Optimal</span>
                </div>
              </div>

              <!-- Analysis Details -->
              <div class="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label class="block text-sm font-medium text-gray-700">Reason for Suggestion</label>
                  <p class="text-gray-700 mt-1">{{ reorderSuggestion.reason || 'Stock level below reorder point' }}</p>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Average Daily Usage</label>
                  <p class="text-lg font-semibold text-gray-900">{{ reorderSuggestion.avg_daily_usage || 0 }}</p>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Lead Time (Days)</label>
                  <p class="text-lg font-semibold text-gray-900">{{ reorderSuggestion.lead_time_days || 0 }}</p>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700">Safety Stock</label>
                  <p class="text-lg font-semibold text-gray-900">{{ reorderSuggestion.safety_stock || 0 }}</p>
                </div>
              </div>
            </template>
          </Card>

          <!-- Related Information -->
          <Card>
            <template #title>
              <div class="flex items-center gap-2">
                <i class="pi pi-link"></i>
                Related Information
              </div>
            </template>
            <template #content>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Reorder Rule</label>
                  <div v-if="reorderSuggestion.reorder_rule" class="p-3 bg-blue-50 rounded-lg">
                    <div class="font-medium text-blue-800">{{ reorderSuggestion.reorder_rule.trigger_type?.replace('_', ' ') }}</div>
                    <div class="text-sm text-blue-600">Min: {{ reorderSuggestion.reorder_rule.min_stock_level }}, Max: {{ reorderSuggestion.reorder_rule.max_stock_level }}</div>
                  </div>
                  <div v-else class="text-gray-500 italic">No associated reorder rule</div>
                </div>

                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Recent Stock Movements</label>
                  <div class="space-y-2">
                    <div v-for="movement in recentMovements" :key="movement.id" class="flex justify-between items-center p-2 bg-gray-50 rounded">
                      <div class="text-sm">
                        <div class="font-medium">{{ movement.type }}</div>
                        <div class="text-gray-500">{{ formatDateTime(movement.created_at) }}</div>
                      </div>
                      <div class="text-sm font-medium" :class="movement.quantity > 0 ? 'text-green-600' : 'text-red-600'">
                        {{ movement.quantity > 0 ? '+' : '' }}{{ movement.quantity }}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </template>
          </Card>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
          <!-- Actions -->
          <Card>
            <template #title>
              <div class="flex items-center gap-2">
                <i class="pi pi-cog"></i>
                Actions
              </div>
            </template>
            <template #content>
              <div class="space-y-3">
                <Button
                  v-if="reorderSuggestion.status === 'pending'"
                  label="Approve & Create Order"
                  icon="pi pi-check"
                  severity="success"
                  class="w-full"
                  @click="approveSuggestion"
                />
                <Button
                  v-if="reorderSuggestion.status === 'pending'"
                  label="Reject Suggestion"
                  icon="pi pi-times"
                  severity="danger"
                  outlined
                  class="w-full"
                  @click="rejectSuggestion"
                />
                <Button
                  label="Modify Quantity"
                  icon="pi pi-pencil"
                  severity="warning"
                  outlined
                  class="w-full"
                  @click="modifyQuantity"
                  :disabled="reorderSuggestion.status !== 'pending'"
                />
                <Button
                  label="View Product"
                  icon="pi pi-eye"
                  severity="secondary"
                  outlined
                  class="w-full"
                  @click="viewProduct"
                />
                <Button
                  label="View Warehouse"
                  icon="pi pi-building"
                  severity="secondary"
                  outlined
                  class="w-full"
                  @click="viewWarehouse"
                />
              </div>
            </template>
          </Card>

          <!-- Approval History -->
          <Card>
            <template #title>
              <div class="flex items-center gap-2">
                <i class="pi pi-clock"></i>
                Approval History
              </div>
            </template>
            <template #content>
              <div class="space-y-3">
                <div v-for="action in approvalHistory" :key="action.id" class="flex items-start gap-3">
                  <div class="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
                  <div class="flex-1">
                    <p class="text-sm text-gray-900">{{ action.description }}</p>
                    <p class="text-xs text-gray-500">{{ formatDateTime(action.created_at) }}</p>
                  </div>
                </div>
                <div v-if="approvalHistory.length === 0" class="text-center text-gray-500 py-4">
                  No approval history
                </div>
              </div>
            </template>
          </Card>

          <!-- Statistics -->
          <Card>
            <template #title>
              <div class="flex items-center gap-2">
                <i class="pi pi-chart-bar"></i>
                Statistics
              </div>
            </template>
            <template #content>
              <div class="space-y-4">
                <div class="flex justify-between items-center">
                  <span class="text-sm text-gray-600">Days Since Generated</span>
                  <span class="font-semibold">{{ daysSinceGenerated }}</span>
                </div>
                <div class="flex justify-between items-center">
                  <span class="text-sm text-gray-600">Urgency Level</span>
                  <Tag
                    :value="urgencyLevel"
                    :severity="getUrgencySeverity(urgencyLevel)"
                  />
                </div>
                <div class="flex justify-between items-center">
                  <span class="text-sm text-gray-600">Estimated Cost</span>
                  <span class="font-semibold">${{ estimatedCost.toFixed(2) }}</span>
                </div>
              </div>
            </template>
          </Card>
        </div>
      </div>

      <!-- Not Found -->
      <div v-else class="text-center py-12">
        <i class="pi pi-exclamation-triangle text-4xl text-gray-400 mb-4"></i>
        <h3 class="text-lg font-medium text-gray-900 mb-2">Reorder Suggestion Not Found</h3>
        <p class="text-gray-600 mb-4">The reorder suggestion you're looking for doesn't exist or has been deleted.</p>
        <Button label="Back to Reorder Suggestions" @click="goBack" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useToast } from 'primevue/usetoast'
import { useRouter, useRoute } from 'vue-router'
import inventoryService from '../../../../services/inventory.service'

const loading = ref(false)
const reorderSuggestion = ref<any>(null)
const recentMovements = ref<any[]>([])
const approvalHistory = ref<any[]>([])
const toast = useToast()
const router = useRouter()
const route = useRoute()

const stockLevelPercentage = computed(() => {
  if (!reorderSuggestion.value) return 0
  const current = reorderSuggestion.value.current_stock || 0
  const reorderPoint = reorderSuggestion.value.reorder_point || 0
  if (reorderPoint === 0) return 100
  return Math.min((current / reorderPoint) * 100, 100)
})

const daysSinceGenerated = computed(() => {
  if (!reorderSuggestion.value?.generated_at) return 0
  const generated = new Date(reorderSuggestion.value.generated_at)
  const now = new Date()
  const diffTime = Math.abs(now.getTime() - generated.getTime())
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24))
})

const urgencyLevel = computed(() => {
  if (!reorderSuggestion.value) return 'normal'
  const current = reorderSuggestion.value.current_stock || 0
  const reorderPoint = reorderSuggestion.value.reorder_point || 0

  if (current === 0) return 'critical'
  if (current <= reorderPoint * 0.5) return 'high'
  if (current <= reorderPoint) return 'medium'
  return 'normal'
})

const estimatedCost = computed(() => {
  if (!reorderSuggestion.value) return 0
  const quantity = reorderSuggestion.value.suggested_quantity || 0
  const cost = reorderSuggestion.value.product?.cost_price || 0
  return quantity * cost
})

const loadReorderSuggestion = async () => {
  loading.value = true
  try {
    const response = await inventoryService.getReorderSuggestion(route.params.id as string)

    if (response.success) {
      reorderSuggestion.value = response.data
      loadRelatedData()
    } else {
      toast.add({
        severity: 'error',
        summary: 'Error',
        detail: response.message || 'Failed to load reorder suggestion',
        life: 3000
      })
    }
  } catch (error: any) {
    toast.add({
      severity: 'error',
      summary: 'Error',
      detail: error.response?.data?.message || 'Failed to load reorder suggestion',
      life: 3000
    })
  } finally {
    loading.value = false
  }
}

const loadRelatedData = async () => {
  // Load recent stock movements
  try {
    const movementsResponse = await inventoryService.getStockMovements({
      product_id: reorderSuggestion.value.product_id,
      limit: 5
    })
    if (movementsResponse.success) {
      recentMovements.value = movementsResponse.data || []
    }
  } catch (error) {
    // Ignore errors for related data
  }

  // Create mock approval history based on the suggestion data
  approvalHistory.value = [
    {
      id: 1,
      description: `Reorder suggestion generated for ${reorderSuggestion.value.product?.name}`,
      created_at: reorderSuggestion.value.generated_at
    },
    ...(reorderSuggestion.value.status !== 'pending' ? [{
      id: 2,
      description: `Suggestion ${reorderSuggestion.value.status}`,
      created_at: reorderSuggestion.value.updated_at
    }] : [])
  ]
}

const goBack = () => {
  router.push({ name: 'inventory.reorder-suggestions.index' })
}

const approveSuggestion = async () => {
  try {
    const response = await inventoryService.approveReorderSuggestion(route.params.id as string)

    if (response.success) {
      toast.add({
        severity: 'success',
        summary: 'Success',
        detail: 'Reorder suggestion approved and purchase order created',
        life: 3000
      })
      reorderSuggestion.value.status = 'approved'
    } else {
      toast.add({
        severity: 'error',
        summary: 'Error',
        detail: response.message || 'Failed to approve reorder suggestion',
        life: 3000
      })
    }
  } catch (error: any) {
    toast.add({
      severity: 'error',
      summary: 'Error',
      detail: error.response?.data?.message || 'Failed to approve reorder suggestion',
      life: 3000
    })
  }
}

const rejectSuggestion = async () => {
  try {
    const response = await inventoryService.rejectReorderSuggestion(route.params.id as string)

    if (response.success) {
      toast.add({
        severity: 'success',
        summary: 'Success',
        detail: 'Reorder suggestion rejected',
        life: 3000
      })
      reorderSuggestion.value.status = 'rejected'
    } else {
      toast.add({
        severity: 'error',
        summary: 'Error',
        detail: response.message || 'Failed to reject reorder suggestion',
        life: 3000
      })
    }
  } catch (error: any) {
    toast.add({
      severity: 'error',
      summary: 'Error',
      detail: error.response?.data?.message || 'Failed to reject reorder suggestion',
      life: 3000
    })
  }
}

const modifyQuantity = () => {
  // This would open a dialog to modify the suggested quantity
  toast.add({
    severity: 'info',
    summary: 'Info',
    detail: 'Modify quantity functionality would be implemented here',
    life: 3000
  })
}

const viewProduct = () => {
  // Navigate to product detail page
  toast.add({
    severity: 'info',
    summary: 'Info',
    detail: 'Product detail navigation would be implemented here',
    life: 3000
  })
}

const viewWarehouse = () => {
  // Navigate to warehouse detail page
  toast.add({
    severity: 'info',
    summary: 'Info',
    detail: 'Warehouse detail navigation would be implemented here',
    life: 3000
  })
}

const formatDateTime = (dateTime: string) => {
  if (!dateTime) return '-'
  return new Date(dateTime).toLocaleString()
}

const getStatusSeverity = (status: string) => {
  switch (status) {
    case 'pending': return 'warning'
    case 'approved': return 'success'
    case 'rejected': return 'danger'
    case 'ordered': return 'info'
    default: return 'secondary'
  }
}

const getPrioritySeverity = (priority: string) => {
  switch (priority) {
    case 'low': return 'secondary'
    case 'medium': return 'info'
    case 'high': return 'warning'
    case 'critical': return 'danger'
    default: return 'secondary'
  }
}

const getUrgencySeverity = (urgency: string) => {
  switch (urgency) {
    case 'normal': return 'secondary'
    case 'medium': return 'info'
    case 'high': return 'warning'
    case 'critical': return 'danger'
    default: return 'secondary'
  }
}

onMounted(() => {
  loadReorderSuggestion()
})
</script>